# start by building the basic container
FROM node:8
ADD hello_node.js /
CMD [ "node", "./hello_node.js" ]


# Create app directory
# WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# COPY package*.json ./
# RUN npm install
# Bundle app source
# COPY . .
# EXPOSE 8080
# CMD [ "npm", "start" ]